### ISSUE TITLE
`PluginException` occurs on IntelliJ IDEA 2024.2.1 warning about deprecated API usage

### ISSUE THREAD

**Issue by christopher-nash** [remotemobprogramming/intellij-mob#107]
When I launch IntelliJ IDEA 2024.2.1, I get the following error message from IntelliJ:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.nowsprinting.intellij_mob.action.start.StartAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.nowsprinting.intellij-mob]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

It appears that this plugin is making a deprecated API call that will be removed soon. Without digging too deep into it, the error message references https://github.com/remotemobprogramming/intellij-mob/blob/master/src/main/kotlin/com/nowsprinting/intellij_mob/action/start/StartAction.kt suggesting it needs to be modified.

**Comment by nowsprinting** [comment]
Thank you for your report!
I try to fix it ASAP.
